language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
# command to install dependencies
install:
  # install all dependencies for full-suite testing
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  # install pycap
  - pip install -e .
script:
- "pytest"
- "cd docs && make html"
